spring.application.name=demo


spring.datasource.url=jdbc:mysql://127.0.0.1:3306/jwt
spring.datasource.username=root
spring.datasource.password=Kumaran@0410

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=Y2hhbmdlLXRoaXMtc2VjcmV0LWtleS10by1zb21ldGhpbmctc3Ryb25n
jwt.expiration-ms=86400000
